[project]
name = "fastapi-tutorial"
version = "0.1.0"
description = "Practice project to learn about FastAPI and backend development"
readme = "README.md"
requires-python = "==3.14.1"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "fastapi>=0.125.0",
    "greenlet>=3.3.0",
    "pre-commit>=4.5.1",
    "pydantic[email]>=2.12.5",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = ["fastapi[standard]", "pytest", "ruff>=0.14.10"]

[tool.ruff]
line-length = 100
target-version = "py314"
exclude = [
    ".venv",
    "alembic"
]

# Enable/Disable rule sets
lint.select = [
    "E", # Pycodestyle errors
    "F", # Pyflakes
    "B", # Bugbear
    "RUF", # Ruff-specific rules
    "T20" # No `print` allowed
]

lint.ignore = [
    "E501", # Don't warn about line length (optional)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
